#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVDIun+crJDTJMV3WWJKUqVj0pF/bouWaCpc6nq/nI4rDdo/lSXiwKgGOkA/kwWxAeliJpLJrVt+M9kjvtEJ/OHYviwqvkY24GkMJCDHHzSItPoHE4Q2lcjp8I/AKIAiEuHsyQR44FnS65GgmHRtsLqajH0ZY7fm2ZXzV1ZJRR60YbC8W1VvkAyiAYSZH0624vI63LZgTCyWEiFR6yqKSemcdFTncI9zjYD/pkQnDIsnZfw4oPIKZtx7C0Mh4hl0vZQ+iPqI87d601+7E7sQFJqHI94cMF3+PWk9wZp4QQmwkWBnYslWy4SIsJceADzLHU1hMx4+vOPml5VgKtsTA7 aws-key
ssh_pwauth: false
disable_root: false
package_update: true
write_files:
  - path: /var/www/html/db.php
    content: |
      <html>
      <head></head>
      <body>
      Diese Seite macht eine Abfrage auf die Datenbank. <br />
      Das ausgeführte Query ist: <i>select Host, User from mysql.user;</i><br /><br />
      Das Resultat: <br />
      <?php
              //database
              $servername = "35.172.192.180";
              $username = "admin";
              $password = "root";
              $dbname = "mysql";

              // Create connection
              $conn = new mysqli($servername, $username, $password, $dbname);
              // Check connection
              if ($conn->connect_error) {
                      die("Connection failed: " . $conn->connect_error);
              }

              $sql = "select Host, User from mysql.user;";
              $result = $conn->query($sql);
              while($row = $result->fetch_assoc()){
                      echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
              }
              //var_dump($result);
      ?>
      </body>
      </html>
    permissions: '0666'
  - path: /var/www/html/info.php
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>

    permissions: '0644'
packages:
  - curl 
  - wget 
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2